typeset -U path cdpath fpath manpath

autoload -Uz compinit
compinit

# for profile in ${(z)NIX_PROFILES}; do
#   fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
# done

zstyle ':completion:*' completer _complete _ignored _approximate
zstyle :compinstall filename '$HOME/.zshrc'

path+="$HOME/.zsh/plugins/zsh-autosuggestions"
fpath+="$HOME/.zsh/plugins/zsh-autosuggestions"
path+="$HOME/.zsh/plugins/zsh-syntax-highlighting"
fpath+="$HOME/.zsh/plugins/zsh-syntax-highlighting"
path+="$HOME/.zsh/plugins/zsh-completions"
fpath+="$HOME/.zsh/plugins/zsh-completions"
path+="$HOME/.zsh/plugins/zsh-vi-mode"
fpath+="$HOME/.zsh/plugins/zsh-vi-mode"

eval "$($HOME/.local/bin/mise activate zsh)"
# Oh-My-Zsh/Prezto calls compinit during initialization,
# calling it twice causes slight start up slowdown
# as all $fpath entries will be traversed again.



# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(docker docker-compose git kube-ps1 pip python golang rust fzf npm zsh-interactive-cd sudo bazel aws mvn terraform)


# source $ZSH/oh-my-zsh.sh



# if [[ -f "$HOME/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh" ]]; then
#   source "$HOME/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
# fi
# if [[ -f "$HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh" ]]; then
#   source "$HOME/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
# fi
# if [[ -f "$HOME/.zsh/plugins/zsh-completions/zsh-completions.plugin.zsh" ]]; then
#   source "$HOME/.zsh/plugins/zsh-completions/zsh-completions.plugin.zsh"
# fi
# if [[ -f "$HOME/.zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh" ]]; then
#   source "$HOME/.zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh"
# fi

source $HOME/.antidote/antidote.zsh
antidote load


# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="50000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


# eval "$(zellij setup --generate-auto-start zsh)"

if [[ $options[zle] = on ]]; then
  eval "$(fzf --zsh)"
fi

setopt appendhistory nomatch notify
unsetopt beep
# End of lines configured by zsh-newuser-install
if [ -f ~/.zkbd/$TERM-${${DISPLAY:t}:-$VENDOR-$OSTYPE} ]; then
  source ~/.zkbd/$TERM-${${DISPLAY:t}:-$VENDOR-$OSTYPE}
  [[ -n ${key[Left]} ]] && bindkey "${key[Left]}" backward-char
  [[ -n ${key[Right]} ]] && bindkey "${key[Right]}" forward-char
  [[ -n ${key[Home]} ]] && bindkey "${key[Home]}" beginning-of-line
  [[ -n ${key[End]} ]] && bindkey "${key[End]}" end-of-lin
  [[ -n ${key[Insert]} ]] && bindkey "${key[Insert]}" overwrite-mode
  [[ -n ${key[Backspace]} ]] && bindkey "${key[Backspace]}" backward-delete-char
  [[ -n ${key[Delete]} ]] && bindkey "${key[Delete]}"  delete-char
  [[ -n ${key[Up]} ]] && bindkey "${key[Up]}" up-line-or-history
  [[ -n ${key[Down]} ]] && bindkey "${key[Down]}" down-line-or-history
  [[ -n ${key[PageUp]} ]] && bindkey "${key[PageUp]}" beginning-of-buffer-or-history
  [[ -n ${key[PageDown]} ]] && bindkey "${key[PageDown]}" end-of-buffer-or-history
fi


if [ -f $HOME/.zshrc_extras ]; then
 source $HOME/.zshrc_extras
fi

function gch() {
  if [ -z "$(git rev-parse --git-dir 2> /dev/null)" ]; then
    return
  fi
  branch=$(git branch --verbose --sort=-committerdate | fzf | awk '{print $1}' | tr -d '[:space:]')
  if [[ ! -z "$branch" ]]; then
    git checkout $branch
  fi
}
zvm_after_init_commands+=('source <(fzf --zsh)')

eval "$(direnv hook zsh)"
eval "$(zoxide init zsh )"

if [[ $TERM != "dumb" ]]; then
  eval "$(starship init zsh)"
fi

# Aliases
alias -- cat=bat
alias -- la='eza -a'
alias -- ll='eza -l'
alias -- lla='eza -la'
alias -- ls=eza
alias -- lt='eza --tree'

# Named Directory Hashes
if [ -e /Users/nfowler/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/nfowler/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# pnpm
export PNPM_HOME="/Users/nfowler/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
