# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "@canva/prettier" = nodeEnv.buildNodePackage {
    name = "_at_canva_slash_prettier";
    packageName = "@canva/prettier";
    version = "3.1.1-canva.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@canva/prettier/-/prettier-3.1.1-canva.0.tgz";
      sha512 = "mHSkojN2PmiJOYUfdmV9gkZXMLH0h6XwCNLCnGdZLgbI4zh5aJFKlPSJnElHLOcYigbQMwAB9UIE64mhoYvYjw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier is an opinionated code formatter";
      homepage = "https://prettier.io";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
